sns/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns= [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
]

sns/main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'main'
urlpatterns = [
    path('', showmain, name='showmain'),
    path('<int:id>', showdetail, name='showdetail'),
    path('new', shownew, name="shownew"),
    path('create', create, name="create"),
    path('update/<int:id>', showupdate, name="showupdate"),
    path('edit/<int:id>', edit, name="edit"),
    path('delete/<int:id>', delete, name="delete"),
    path('likes/<int:blog_id>', likes, name="likes"),
]

sns/sns/urls.py
from django.contrib import admin
from django.urls import path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.showmain),
    path('<int:id>', views.showdetail, name='showdetail'),
    path('new/', views.shownew, name="shownew"),
    path('create/', views.create, name="create"),
]

sns/users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path('mypage/<int:id>', mypage, name="mypage"),
    path('follow/<int:id>', follow, name="follow"),
]

sns/accounts/models.py
from django.db import models

# Create your models here.

sns/main/models.py
from django.db import models
from users.models import User

# Create your models here.
class Blog(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateField()
    body = models.TextField()
    like = models.ManyToManyField(User, related_name='likes',blank=True)
    like_count = models.PositiveIntegerField(default=0) #0또는 양수만 받는 필드

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:20]
    

sns/users/models.py
from django.db import models
from django.contrib.auth.models import User

from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followings = models.ManyToManyField("self", related_name="followers", symmetrical=False)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

sns/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth

# Create your views here.
def login(request):
    if request.method == 'POST':
        usr = request.POST['username']
        pwd = request.POST['password']
        user = auth.authenticate(request, username=usr, password=pwd)
        if user is not None:
            auth.login(request,user)
            return redirect('main:showmain')
        else:
            return render(request, 'login.html')
        pass
    elif request.method == 'GET':
        return render(request, 'login.html')
    
def logout(request):
    auth.logout(request)
    return redirect('main:showmain')

sns/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Blog, User

from django.views.decorators.http import require_POST
# 2-2 response를 변환하는 가장 가본 함수, html 파일, 이미지 등 다양한 응답
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
# 2-3 딕셔너리를 json 형식으로 바꾸기 위해
import json

# Create your views here.
def showmain(request):
    blogs = Blog.objects.all()
    return render(request, 'main/main.html', {'blogs':blogs})

def showdetail(request, id):
    blog = get_object_or_404(Blog, pk=id)
    return render(request, 'main/detail.html', {'blog':blog})

def shownew(request):
    return render(request, 'main/new.html')

def create(request):
    new_blog = Blog()
    new_blog.title = request.POST['title']
    new_blog.writer = request.user
    new_blog.pub_date = timezone.now()
    new_blog.body = request.POST['body']
    new_blog.save()
    return redirect('main:showdetail', new_blog.id)

def showupdate(request, id):
    update_blog = Blog.objects.get(id=id)
    return render(request, 'main/update.html', {'blog':update_blog})

def edit(request, id):
    update_blog = Blog.objects.get(id=id)
    update_blog.title = request.POST['title']
    update_blog.writer = request.user
    update_blog.pub_date = timezone.now()
    update_blog.body = request.POST['body']
    update_blog.save()
    return redirect('main:showdetail', update_blog.id)

def delete(request, id):
    delete_blog = Blog.objects.get(id=id)
    delete_blog.delete()
    return redirect('main:showmain')

def likes(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    if request.user in blog.like.all():
        blog.like.remove(request.user)
        blog.like_count -= 1
        blog.save()
    else:
        blog.like.add(request.user)
        blog.like_count += 1
        blog.save()
    return redirect('main:showdetail', blog.id)

sns/users/views.py
from django.shortcuts import render, redirect, get_object_or_404

from main.models import Blog
from django.contrib.auth.models import User

def mypage(request, id):
    user = get_object_or_404(User, pk=id)
    context = {
        'user':user,
        'blogs':Blog.objects.filter(writer=user),
        'followings' : user.profile.followings.all(),
        'followers' : user.profile.followers.all(),
    }
    return render(request, 'users/mypage.html', context)

def follow(request, id):
    user=request.user
    followed_user=get_object_or_404(User, pk=id)
    is_follower=user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

sns/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form actinon="{% url 'accounts:login' %}" method="post">
    {%csrf_token%}
    id : <input type="text" name="username"><br>
    password : <input type="password" name="password"><br>
    <input type="submit" value="login">
</form>

{% endblock %}

sns/main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>    
    <title>Document</title>
</head>
<body>
    {% include 'shared/_navbar.html' %}

    <div class="content">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

sns/main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{blog.title}}</h1>


<!-- 'user:mypage' url로 게시글 작성자의 아이디와 함께 href 연결! -->
{% if blog.writer %}
<a href="{% url 'users:mypage' blog.writer.id %}">작성자 : {{blog.writer}}</a><br>
{% else %}
작성자 : 알 수 없음<br>
{% endif %}

{{blog.body}}<br>
{{blog.pub_date}}

<!-- 좋아요 버튼 -->
<a href="{% url 'main:likes' blog.id %}">
    {% if user in blog.like.all %}
    취소
    {% else %}
    좋아요
    {% endif %}
</a>

<!-- 개수 -->
{{blog.like_count}}개

<a href="{% url 'main:showupdate' blog.id %}">수정하기</a>
<a href="{% url 'main:delete' blog.id %}">삭제하기</a>

{% endblock %}

sns/main/templates/main/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>글목록</h1>
<div class="container">
    <div class="row">
        {% for blog in blogs %}
            <div class="col-md-3 col-6 item_list__card">
                <div class="card" style="font-family: 'scd3';">
                        <div class="card-body" style="font-size:16px">
                            <h5 class="card-title">{{ blog.title }}</h5>
                            {% if blog.writer %}
                            작성자 : {{blog.writer}}<br>
                            {% else %}
                            작성자 : None<br>
                            {% endif %}
                            내용 : {{blog.summary}}
                            <a href="{% url 'main:showdetail' blog.id %}">...자세히</a><br>
                            {{blog.pub_date}}
                            <br>
                        </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

sns/main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'main:create' %}" method="post">
    {%csrf_token%}
    <p>제목 : <input type="text" name="title"></p>
    <!-- <p>작성자 : <input type="text" name="writer"></p> -->
    <p>내용 : <input type="text" name="body"></p>
    <button type="submit">제출하기</button>
</form>

{% endblock %}

sns/main/templates/main/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'main:edit' blog.id %}" method="post">
    {%csrf_token%}
    <p>제목 : <input type="text" name="title" value="{{blog.title}}"></p>
    <p>작성자 : <input type="text" name="writer" value="{{blog.writer}}"></p>
    <p>내용 : <input type="text" name="body" value="{{blog.body}}"></p>
    <button type="submit">제출하기</button>
</form>

{% endblock %}

sns/main/templates/shared/_navbar.html
{%if user.is_authenticated%}

<nav class="navbar bg-light fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:showmain' %}">므쨍이 으르렁</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
        <div class="offcanvas-title" id="offcanvasNavbarLabel">
            <a href="{% url 'accounts:logout' %}">logout</a>
        </div>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:shownew' %}">Create</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:mypage' user.id %}">My page</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

{%else%}

<nav class="navbar bg-light fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:showmain' %}">므쨍이 으르렁</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
            <div class="offcanvas-title" id="offcanvasNavbarLabel">
                <a href="{% url 'accounts:login' %}">login</a>
            </div>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:shownew' %}">Create</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=#>My page</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

        {%endif%}

sns/users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <h3>{{user.username}}</h3>
        {% if request.user != user %}
            {% if request.user.profile in user.profile.followers.all %}
                <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-outline-info">언팔로우</button></a>
            {% else %}
                <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
            {% endif %}
        {% endif %}

        <p>팔로워<br>{{user.profile.followers.count}}명</p>
        {%for follower in user.profile.followers.all %}
            <a href="{% url 'users:mypage' follower.user.id %}">{{ follower.user.username }}</a>
        {% endfor %}

        <p>팔로잉<br>{{user.profile.followings.count}}명</p>
        {% for following in user.profile.followings.all %}
            <a href="{% url 'users:mypage' following.user.id %}">{{ following.user.username }}</a>
        {% endfor %}
        
    <div>
        {% for blog in blogs %}
        <a href="{% url 'main:showdetail' blog.id %}">{{blog.title}}</a>
        {% endfor %}
    </div>
</div>

{% endblock %}